AppBundle\Entity\ProductDiscountGroup:
    type: entity
    table: product_discount_group
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        limit1:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        discount1:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
        limit2:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        discount2:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
        limit3:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        discount3:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
    lifecycleCallbacks: {  }
