AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        inStock:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: in_stock
    oneToMany:
        images:
            targetEntity: ProductImageList
            mappedBy: product
            cascade: ["persist"]
            orphanRemoval: true
    manyToOne:
        discount:
            targetEntity: ProductDiscountGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                discount_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
