AppBundle\Entity\ProductImageList:
    type: entity
    table: product_image_list
    indexes:
        product_id:
            columns:
                - product_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        src:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        product:
            targetEntity: Product
            cascade: ["persist","refresh"]
            inversedBy: images
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: true
    lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]
